### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by bcrabbe** [mattaylor/emoosc#2]
Hi, 
Following your installation commands im getting an error: 

npm ERR! missing script: config.js

Im in the directory and the config.js is there too... do you have any tips?
Thank you

Heres the full error log: 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.9.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   '--',
1 verbose cli   './config.js' ]
2 info using npm@5.6.0
3 info using node@v7.9.0
4 verbose stack Error: missing script: ./config.js
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:402:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:357:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:400:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:348:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:449:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
5 verbose cwd /Users/bencrabbe/Documents/code/emoosc
6 verbose Darwin 16.7.0
7 verbose argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "run" "--" "./config.js"
8 verbose node v7.9.0
9 verbose npm  v5.6.0
10 error missing script: ./config.js
11 verbose exit [ 1, true ]

**Comment by mattaylor** [comment]
just commited a fix - try again.

**Comment by bcrabbe** [comment]
same problem

**Comment by elliothogg** [comment]
I just tried the fix and got this:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   '--',
1 verbose cli   'config.js' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose stack Error: missing script: config.js
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:402:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:357:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:400:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:280:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
5 verbose cwd C:\Users\Elliot\Desktop\emoosc-master\node_modules\emoosc
6 verbose Windows_NT 6.3.9600
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "--" "config.js"
8 verbose node v8.9.4
9 verbose npm  v5.6.0
10 error missing script: config.js
11 verbose exit [ 1, true ]
