### ISSUE TITLE
errors ocurrred

### ISSUE THREAD

**Issue by sashawa** [mattaylor/emoosc#4]
Hi, I tried to use your library and I get this mistake (below). What can you advise? thank you very much!
 
node index.js 
/Users/rustemvaliev/emoosc/index.js:8
var emo = new Emocore(conf.emo.newSession({ project:'OSC', status:'active' }));
                               ^

TypeError: conf.emo.newSession is not a function
    at Object.<anonymous> (/Users/rustemvaliev/emoosc/index.js:8:32)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)

this is config.js:

module.exports = { 
  emo: { 
    username: 'rustvt',
    password: 'Jaco03071984',
    license : 'advanced',
    client_id:'vDeLqktK49v18FpEKsJVZJVsxAewxkQ8rMdLEr1N',
    client_secret:'yYs24r1tLYhcigvGzwh8arrSKEqhDpOH135fdcDMGlbipdhQ1cuzC4sRxxmziEBZHXu8SxuD6ulB3f2zHavO6BPd2nIJqEQH3uVLyRJ2bE2qH4WM8RW556BLAm8ofXbz'
  },
  osc: {
    port : 7001,
    host: 'localhost',
    protocol: 'udp',
    streams : ['cog', 'pow']
  }
}

**Comment by blairzaye** [comment]
did you manage to sort this? im getting the same issues

**Comment by mattaylor** [comment]
try again - should be fixed now, although I am unable to test as I no longer work for emotiv and do not currently have access to headsets
